### ISSUE TITLE
Camhack for silent hill

### ISSUE THREAD

**Issue by aggugigg** [moonlessformless/ps2_cam_acolyte#7]
First, sorry for my english, i speak spanish.
Now, i was trying to modify the camera in the game silent hill origins, the idea is to obtain a "modern camera" in third person, your code is brilliant but I can't do it, I would appreciate if you could help me with that!

**Comment by moonlessformless** [comment]
This is a killer idea and definitely possible. I'm going to work on this!

**Comment by moonlessformless** [comment]
Added to v0.04

**Comment by aggugigg** [comment]
THANK YOU VERY MUCH, it is an incredible job, thank you very much for making it possible, you are the best of 2024 THANK YOU!
